<?php
require('auth.php');
require('bridge_client.php');
$routers = bridge_routers();
$routerId = isset($_GET['router']) ? (int)$_GET['router'] : (isset($_SESSION['router']) ? (int)$_SESSION['router'] : null);
$activeRouter = $routerId !== null && isset($routers[$routerId]) ? $routers[$routerId] : null;
$vlanList = [];$error='';
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['action'],$_POST['id'],$_POST['router'])){ $routerId=(int)$_POST['router']; $res=bridge_post('/vlan/toggle',['router_id'=>$routerId,'id'=>trim($_POST['id']),'action'=>$_POST['action']==='enable'?'enable':'disable']); header("Location: manage_vlan.php?router=$routerId"); exit; }
if($activeRouter){$res=bridge_post('/vlan/list',['router_id'=>$routerId]); if(!empty($res['ok'])){$vlanList=$res['data']??[];}else{$error=$res['detail']??$res['error']??'Gagal mengambil VLAN dari bridge.';}}
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>CAS VLAN</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets_cas.css?v=20260505-ux1" rel="stylesheet"></head><body class="cas-body"><div class="cas-shell"><div class="cas-topbar"><div class="cas-brand"><div class="cas-logo">🌐</div><div><h1 class="cas-title">CAS VLAN Control</h1><p class="cas-subtitle">Client Access Control · Enable/Disable VLAN via bridge</p></div></div><div class="cas-actions"><a href="index.php" class="btn btn-light">Dashboard</a><a href="tutorial.php" class="btn btn-outline-light">Tutorial</a><a href="tambah_user.php" class="btn btn-outline-light">Pengguna</a><a href="logout.php" class="btn btn-danger">Logout</a></div></div><div class="cas-card mb-3"><form method="GET" class="cas-router-panel"><select name="router" class="form-select" onchange="this.form.submit()"><option disabled <?= $routerId===null?'selected':'' ?>>Pilih Router</option><?php foreach($routers as $id=>$r):?><option value="<?=h($id)?>" <?=$routerId===(int)$id?'selected':''?>><?=h($r['name']??'Router')?> · <?=h($r['ip']??'-')?>:<?=h($r['port']??'-')?></option><?php endforeach;?></select></form></div><?php if($error):?><div class="cas-alert cas-alert-danger mb-3">❌ <?=h($error)?></div><?php elseif($activeRouter):?><div class="cas-alert cas-alert-success mb-3">✅ Data VLAN dari bridge: <strong><?=h($activeRouter['name'])?></strong></div><div class="cas-card cas-table-card"><div class="cas-table-head bg-grad-dark"><h5 class="mb-0">Daftar VLAN Interface</h5><span><?=count($vlanList)?> VLAN</span></div><div class="cas-table-wrap table-responsive"><table class="table table-hover table-striped"><thead><tr><th>Nama Interface</th><th>VLAN ID</th><th>Interface Asal</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($vlanList as $vlan):?><tr><td><strong><?=h($vlan['name']??'-')?></strong></td><td><?=h($vlan['vlan-id']??'-')?></td><td><?=h($vlan['interface']??'-')?></td><td><?=($vlan['disabled']??'false')==='true'?'<span class="badge bg-danger">Disabled</span>':'<span class="badge bg-success">Enabled</span>'?></td><td><form method="POST"><input type="hidden" name="id" value="<?=h($vlan['.id']??'')?>"><input type="hidden" name="router" value="<?=h($routerId)?>"><input type="hidden" name="action" value="<?=($vlan['disabled']??'false')==='true'?'enable':'disable'?>"><button class="btn btn-sm <?=($vlan['disabled']??'false')==='true'?'btn-success':'btn-danger'?>" onclick="return confirm('Lanjutkan aksi VLAN ini?')"><?=($vlan['disabled']??'false')==='true'?'Enable':'Disable'?></button></form></td></tr><?php endforeach;?></tbody></table></div></div><?php else:?><div class="cas-alert cas-alert-warning">Pilih router terlebih dahulu.</div><?php endif;?><p class="cas-footer-note">CAS v1.1 · Client Access Control</p></div></body></html>
